# -*- coding: utf-8 -*-
"""BKDS01 - Muhammad Afif Naufal Ardani Pertemuan 2(Hungarian.data) .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LxZIRO_DbOW3ih9QbiVLEYzv5ttWOC0y

## **PROJECT BIMBINGAN KARIR DATA SCIENCE HUNGARIAN**

> Nama  : Muhammad Afif Naufal Ardani

> NIM   : A11.2020.12633

> Kelas : BKDS01 - Data Scientist

# **1) Pengumpulan Data**

Dataset yang akan digunakan adalah dataset yang bersumber dari https://archive.ics.uci.edu/dataset/45/heart+disease

Secara spesifik dataset yang digunakan pada project ini adalah dataset dengan nama "hungarian.data"

# **2) Menelaah Data**
"""

# File Library yang digunakan untuk project Hungarian.data
import itertools
import pandas as pd
import numpy as np
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score
import streamlit as st
import time
import pickle

# from xgboost import XGBClassifier


with open("data/hungarian.data", encoding='Latin1') as file:
  lines = [line.strip() for line in file]

data = itertools.takewhile(
  lambda x: len(x) == 76,
  (' '.join(lines[i:(i + 10)]).split() for i in range(0, len(lines), 10))
)

df = pd.DataFrame.from_records(data)

df = df.iloc[:, :-1]
df = df.drop(df.columns[0], axis=1)
df = df.astype(float)

df.replace(-9.0, np.NaN, inplace=True)

df_selected = df.iloc[:, [1, 2, 7, 8, 10, 14, 17, 30, 36, 38, 39, 42, 49, 56]]

column_mapping = {
  2: 'age',
  3: 'sex',
  8: 'cp',
  9: 'trestbps',
  11: 'chol',
  15: 'fbs',
  18: 'restecg',
  31: 'thalach',
  37: 'exang',
  39: 'oldpeak',
  40: 'slope',
  43: 'ca',
  50: 'thal',
  57: 'target'
}

df_selected.rename(columns=column_mapping, inplace=True)

columns_to_drop = ['ca', 'slope','thal']
df_selected = df_selected.drop(columns_to_drop, axis=1)

meanTBPS = df_selected['trestbps'].dropna()
meanChol = df_selected['chol'].dropna()
meanfbs = df_selected['fbs'].dropna()
meanRestCG = df_selected['restecg'].dropna()
meanthalach = df_selected['thalach'].dropna()
meanexang = df_selected['exang'].dropna()

meanTBPS = meanTBPS.astype(float)
meanChol = meanChol.astype(float)
meanfbs = meanfbs.astype(float)
meanthalach = meanthalach.astype(float)
meanexang = meanexang.astype(float)
meanRestCG = meanRestCG.astype(float)

meanTBPS = round(meanTBPS.mean())
meanChol = round(meanChol.mean())
meanfbs = round(meanfbs.mean())
meanthalach = round(meanthalach.mean())
meanexang = round(meanexang.mean())
meanRestCG = round(meanRestCG.mean())

fill_values = {
  'trestbps': meanTBPS,
  'chol': meanChol,
  'fbs': meanfbs,
  'thalach':meanthalach,
  'exang':meanexang,
  'restecg':meanRestCG
}

df_clean = df_selected.fillna(value=fill_values)
df_clean.drop_duplicates(inplace=True)

X = df_clean.drop("target", axis=1)
y = df_clean['target']

smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)

# pickle.dump(XGBClassifier,open("model/xgb_model.pkl", 'wb'))

model = pickle.load(open("xgboost.pkl", 'rb'))

# model = XGBClassifier()
# model.fit(X, y)

y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
accuracy = round((accuracy * 100), 2)

df_final = X
df_final['target'] = y

# ========================================================================================================================================================================================

# STREAMLIT
st.set_page_config(
  page_title = "CEPEJAN (Berdasarkan Hungarian.data)",
  page_icon = ":fire:"
)

st.title("CEPEJAN")
st.write("**Cek Penyakit Jantung**")
st.write(f"**_Model's Accuracy_** :  :green[**{accuracy}**] % (:blue[_Tahap Pengembangan_])")
st.write("")

tab1, tab2 = st.tabs(["**Prediksi Satuan**", "**Prediksi Tabel**"])

with tab1:
  st.sidebar.header("**Masukkan Data**")

  age = st.sidebar.number_input(label=":violet[**Umur**]", min_value=df_final['age'].min(), max_value=df_final['age'].max())
  st.sidebar.write(f":orange[Min] Umur: :orange[**{df_final['age'].min()}**], :red[Maks] Umur: :red[**{df_final['age'].max()}**]")
  st.sidebar.write("")

  sex_sb = st.sidebar.selectbox(label=":violet[**Jenis Kelamin**]", options=["Pria", "Wanita"])
  st.sidebar.write("")
  st.sidebar.write("")
  if sex_sb == "Pria":
    sex = 1
  elif sex_sb == "Wanita":
    sex = 0
  # -- Value 0: Wanita
  # -- Value 1: Pria

  cp_sb = st.sidebar.selectbox(label=":violet[**Jenis Nyeri Dada**]", options=["Typical angina", "Atypical angina", "Non-anginal pain", "Asymptomatic"])
  st.sidebar.write("")
  st.sidebar.write("")
  if cp_sb == "Typical angina":
    cp = 1
  elif cp_sb == "Atypical angina":
    cp = 2
  elif cp_sb == "Non-anginal pain":
    cp = 3
  elif cp_sb == "Asymptomatic":
    cp = 4
  # -- Value 1: typical angina
  # -- Value 2: atypical angina
  # -- Value 3: non-anginal pain
  # -- Value 4: asymptomatic

  trestbps = st.sidebar.number_input(label=":violet[**Tekanan Darah saat Istirahat** (dalam mm Hg)]", min_value=df_final['trestbps'].min(), max_value=df_final['trestbps'].max())
  st.sidebar.write(f":orange[Min] value: :orange[**{df_final['trestbps'].min()}**], :red[Maks] value: :red[**{df_final['trestbps'].max()}**]")
  st.sidebar.write("")

  chol = st.sidebar.number_input(label=":violet[**Kolesterol pada Darah** (in mg/dl)]", min_value=df_final['chol'].min(), max_value=df_final['chol'].max())
  st.sidebar.write(f":orange[Min] value: :orange[**{df_final['chol'].min()}**], :red[Maks] value: :red[**{df_final['chol'].max()}**]")
  st.sidebar.write("")

  fbs_sb = st.sidebar.selectbox(label=":violet[**Kadar Gula Darah saat Puasa > 120 mg/dl?**]", options=["Tidak", "Benar"])
  st.sidebar.write("")
  st.sidebar.write("")
  if fbs_sb == "Tidak":
    fbs = 0
  elif fbs_sb == "Benar":
    fbs = 1
  # -- Value 0: false
  # -- Value 1: true

  restecg_sb = st.sidebar.selectbox(label=":violet[**Hasil EKG (Elektrodiagram)**]", options=["Normal", "Having ST-T wave abnormality", "Showing left ventricular hypertrophy"])
  st.sidebar.write("")
  st.sidebar.write("")
  if restecg_sb == "Normal":
    restecg = 0
  elif restecg_sb == "Having ST-T wave abnormality":
    restecg = 1
  elif restecg_sb == "Showing left ventricular hypertrophy":
    restecg = 2
  # -- Value 0: normal
  # -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST  elevation or depression of > 0.05 mV)
  # -- Value 2: showing probable or definite left ventricular hypertrophy by Estes' criteria

  thalach = st.sidebar.number_input(label=":violet[**Detak Jantung Maksimum**]", min_value=df_final['thalach'].min(), max_value=df_final['thalach'].max())
  st.sidebar.write(f":orange[Min] value: :orange[**{df_final['thalach'].min()}**], :red[Maks] value: :red[**{df_final['thalach'].max()}**]")
  st.sidebar.write("")

  exang_sb = st.sidebar.selectbox(label=":violet[**Nyeri Dada saat Olahraga?**]", options=["Tidak", "Benar"])
  st.sidebar.write("")
  st.sidebar.write("")
  if exang_sb == "Tidak":
    exang = 0
  elif exang_sb == "Benar":
    exang = 1
  # -- Value 0: No
  # -- Value 1: Yes

  oldpeak = st.sidebar.number_input(label=":violet[**Perubahan EKG saat Olahraga**]", min_value=df_final['oldpeak'].min(), max_value=df_final['oldpeak'].max())
  st.sidebar.write(f":orange[Min] value: :orange[**{df_final['oldpeak'].min()}**], :red[Maks] value: :red[**{df_final['oldpeak'].max()}**]")
  st.sidebar.write("")

  data = {
    'Umur': age,
    'Jenis Kelamin': sex_sb,
    'Jenis Nyeri Dada': cp_sb,
    'Tekanan Darah saat Istirahat': f"{trestbps} mm Hg",
    'Kolesterol pada Darah': f"{chol} mg/dl",
    'Kadar Gula Darah saat Puasa > 120 mg/dl?': fbs_sb,
    'Hasil EKG': restecg_sb,
    'Detak Jantung Maksimum': thalach,
    'Nyeri Dada saat Olahraga': exang_sb,
    'Perubahan EKG saat Olahraga': oldpeak,
  }

  preview_df = pd.DataFrame(data, index=['input'])

  st.header("Data Masukan User sebagai DataFrame")
  st.write("")

  st.dataframe(preview_df.iloc[:, :6])
  st.write("")

  st.dataframe(preview_df.iloc[:, 6:])
  st.write("")

  result = ":violet[-]"

  predict_btn = st.button("**Kalkulasi**", type="primary")

  st.write("")
  if predict_btn:
    inputs = [[age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak]]
    prediction = model.predict(inputs)[0]

    bar = st.progress(0)
    status_text = st.empty()

    for i in range(1, 101):
      status_text.text(f"{i}% complete")
      bar.progress(i)
      time.sleep(0.01)
      if i == 100:
        time.sleep(1)
        status_text.empty()
        bar.empty()

    if prediction == 0:
      result = ":green[**Sehat**]"
    elif prediction == 1:
      result = ":orange[**Sakit Jantung Level 1**]"
    elif prediction == 2:
      result = ":orange[**Sakit Jantung Level 2**]"
    elif prediction == 3:
      result = ":red[**Sakit Jantung Level 3**]"
    elif prediction == 4:
      result = ":red[**Sakit Jantung Level 4**]"

  st.write("")
  st.write("")
  st.subheader("Prediksi:")
  st.subheader(result)

with tab2:
  st.header("Prediksi Banyak Data")

  sample_csv = df_final.iloc[:5, :-1].to_csv(index=False).encode('utf-8')

  st.write("")
  st.download_button("Unduh Contoh CSV", data=sample_csv, file_name='sample_heart_disease_parameters.csv', mime='text/csv')

  st.write("")
  st.write("")
  file_uploaded = st.file_uploader("Unggah CSV file", type='csv')

  if file_uploaded:
    uploaded_df = pd.read_csv(file_uploaded)
    prediction_arr = model.predict(uploaded_df)

    bar = st.progress(0)
    status_text = st.empty()

    for i in range(1, 70):
      status_text.text(f"{i}% complete")
      bar.progress(i)
      time.sleep(0.01)

    result_arr = []

    for prediction in prediction_arr:
      if prediction == 0:
        result = "Sehat"
      elif prediction == 1:
        result = "Sakit Jantung Level 1"
      elif prediction == 2:
        result = "Sakit Jantung Level 2"
      elif prediction == 3:
        result = "Sakit Jantung Level 3"
      elif prediction == 4:
        result = "Sakit Jantung Level 4"
      result_arr.append(result)

    st.write("")
    uploaded_result = pd.DataFrame({'Hasil Prediksi': result_arr})

    for i in range(70, 101):
      status_text.text(f"{i}% complete")
      bar.progress(i)
      time.sleep(0.01)
      if i == 100:
        time.sleep(1)
        status_text.empty()
        bar.empty()

    col1, col2 = st.columns([1, 2])

    with col1:
      st.dataframe(uploaded_result)
    with col2:
      st.dataframe(uploaded_df)
